load("@prysm//tools/go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "authenticator.go",
        "codec.go",
        "hasher.go",
        "reassembler.go",
        "segment.go",
        "tree.go",
    ],
    importpath = "github.com/OffchainLabs/prysm/v7/container/segments",
    visibility = ["//visibility:public"],
    deps = [
        "//crypto/hash:go_default_library",
        "//math:go_default_library",
        "//proto/prysm/v1alpha1:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    size = "small",
    srcs = [
        "codec_test.go",
        "reassembler_test.go",
        "segments_test.go",
    ],
    embed = [":go_default_library"],
    deps = [
        "//proto/prysm/v1alpha1:go_default_library",
        "//testing/require:go_default_library",
    ],
)
