package segments

// GF(2^8) arithmetic for the Reed-Solomon code, generated by x^8+x^4+x^3+x^2+1 (0x11d).
//
// A dependency-free table implementation: 64 KiB of multiplication table built once at init,
// and straightforward loops over it. Correct and slow; see the note in rs.go.

// gfMul is the full 256x256 multiplication table (64 KiB), built once at init. Row 0 and
// column 0 are all zero, which the encode/decode loops rely on to skip nothing.
var gfMul [256][256]byte

// gfInv is the multiplicative inverse; gfInv[0] is unused and left zero.
var gfInv [256]byte

func init() {
	var exp [512]byte
	var log [256]byte
	x := byte(1)
	for i := 0; i < 255; i++ {
		exp[i] = x
		log[x] = byte(i)
		// Multiply by the generator 2 in GF(2^8) mod 0x11d.
		hi := x&0x80 != 0
		x <<= 1
		if hi {
			x ^= 0x1d
		}
	}
	for i := 255; i < 512; i++ {
		exp[i] = exp[i-255]
	}
	for a := 1; a < 256; a++ {
		for b := 1; b < 256; b++ {
			gfMul[a][b] = exp[int(log[a])+int(log[b])]
		}
		gfInv[a] = exp[255-int(log[a])]
	}
}

// gfMulSlice computes out ^= c * in over a byte slice. A no-op when c is zero.
func gfMulSlice(out, in []byte, c byte) {
	if c == 0 {
		return
	}
	if c == 1 {
		for i := range in {
			out[i] ^= in[i]
		}
		return
	}
	mt := &gfMul[c]
	for i := range in {
		out[i] ^= mt[in[i]]
	}
}

// gfMatMul multiplies an rows x cols matrix (row-major) by cols data shards of equal
// length, writing rows output shards. Output shards must be zeroed by the caller.
func gfMatMul(out [][]byte, matrix []byte, cols int, in [][]byte) {
	for r := range out {
		row := matrix[r*cols : (r+1)*cols]
		for c, shard := range in {
			gfMulSlice(out[r], shard, row[c])
		}
	}
}

// gfInvertMatrix inverts an n x n matrix (row-major) in place via Gauss-Jordan,
// returning false when the matrix is singular.
func gfInvertMatrix(m []byte, n int) bool {
	// Augment with the identity.
	aug := make([]byte, n*2*n)
	for r := 0; r < n; r++ {
		copy(aug[r*2*n:], m[r*n:(r+1)*n])
		aug[r*2*n+n+r] = 1
	}
	for col := 0; col < n; col++ {
		// Find a pivot.
		pivot := -1
		for r := col; r < n; r++ {
			if aug[r*2*n+col] != 0 {
				pivot = r
				break
			}
		}
		if pivot < 0 {
			return false
		}
		if pivot != col {
			for i := 0; i < 2*n; i++ {
				aug[col*2*n+i], aug[pivot*2*n+i] = aug[pivot*2*n+i], aug[col*2*n+i]
			}
		}
		// Normalize the pivot row.
		inv := gfInv[aug[col*2*n+col]]
		for i := 0; i < 2*n; i++ {
			aug[col*2*n+i] = gfMul[inv][aug[col*2*n+i]]
		}
		// Eliminate the column everywhere else.
		for r := 0; r < n; r++ {
			if r == col {
				continue
			}
			c := aug[r*2*n+col]
			if c == 0 {
				continue
			}
			for i := 0; i < 2*n; i++ {
				aug[r*2*n+i] ^= gfMul[c][aug[col*2*n+i]]
			}
		}
	}
	for r := 0; r < n; r++ {
		copy(m[r*n:(r+1)*n], aug[r*2*n+n:r*2*n+2*n])
	}
	return true
}
