load("@prysm//tools/go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "msgid.go",
        "pullgate.go",
        "pushwidth.go",
        "segmentgossip.go",
    ],
    importpath = "github.com/OffchainLabs/prysm/v7/beacon-chain/p2p/internal/segmentgossip",
    visibility = ["//beacon-chain/p2p:__subpackages__"],
    deps = [
        "//beacon-chain/p2p/encoder:go_default_library",
        "//config/params:go_default_library",
        "//proto/prysm/v1alpha1:go_default_library",
        "@com_github_libp2p_go_libp2p//core/peer:go_default_library",
        "@com_github_libp2p_go_libp2p_pubsub//:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = [
        "msgid_test.go",
        "pullgate_test.go",
        "pushwidth_test.go",
        "segmentgossip_test.go",
    ],
    embed = [":go_default_library"],
    deps = [
        "//beacon-chain/p2p/testing:go_default_library",
        "//config/params:go_default_library",
        "//proto/prysm/v1alpha1:go_default_library",
        "//testing/require:go_default_library",
        "@com_github_golang_snappy//:go_default_library",
        "@com_github_libp2p_go_libp2p//core/peer:go_default_library",
        "@com_github_libp2p_go_libp2p_pubsub//:go_default_library",
        "@com_github_libp2p_go_libp2p_pubsub//pb:go_default_library",
    ],
)
