package partialdatacolumnbroadcaster

import (
	"sync"

	"github.com/OffchainLabs/prysm/v7/consensus-types/blocks"
)

// Why this exists.
//
// A metadata storm on the row axis was diagnosed three times from aggregate counters and the
// mechanism was wrong each time -- bandwidth, then host CPU, then a per-RPC full-mesh fanout whose
// headline ratio turned out to be the summed count divided by the mesh degree. The reason no
// argument settled it is that every candidate mechanism produces the same aggregate: N messages of
// M bytes. What distinguishes them is *which comparison in partialForPeer fired*, and nothing
// recorded that.
//
// So: count actions by reason, per axis, generated at the point of decision. Two properties matter.
//
// Generated, not admitted. These counters increment when an action is built, whereas the gossipsub
// tracer counts sends after queue admission. The difference between the two is the drop rate, which
// is otherwise invisible -- the extension's send returns no acceptance signal, and gossipsub's drop
// recovery preserves only control messages. Comparing them is the cheapest available check on
// whether announcements are being silently discarded.
//
// Multi-label. One action can carry cells and metadata together, and a request difference
// short-circuits the availability test, so a single label per action would mis-attribute. The
// counters are therefore keyed by the whole reason set, and Fold sums whichever bits a caller asks
// about.
//
// See notes/rowdas/plan-repair.md section 3.

// actionReasonCounts tallies publish actions by reason set and by axis.
type actionReasonCounts struct {
	mu   sync.Mutex
	rows map[blocks.ActionReason]int
	cols map[blocks.ActionReason]int
}

func newActionReasonCounts() *actionReasonCounts {
	return &actionReasonCounts{
		rows: make(map[blocks.ActionReason]int),
		cols: make(map[blocks.ActionReason]int),
	}
}

func (c *actionReasonCounts) record(isRow bool, reason blocks.ActionReason) {
	if reason == 0 {
		return
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	if isRow {
		c.rows[reason]++
		return
	}
	c.cols[reason]++
}

// snapshot copies both tallies, so a reader never holds the lock while formatting.
func (c *actionReasonCounts) snapshot() (rows, cols map[blocks.ActionReason]int) {
	c.mu.Lock()
	defer c.mu.Unlock()
	rows = make(map[blocks.ActionReason]int, len(c.rows))
	for reason, n := range c.rows {
		rows[reason] = n
	}
	cols = make(map[blocks.ActionReason]int, len(c.cols))
	for reason, n := range c.cols {
		cols[reason] = n
	}

	return rows, cols
}

// ActionReasonCounts reports publish actions generated by this broadcaster, keyed by reason set,
// split by axis. Intended for experiments: it is the attribution that decides which half of the
// announce policy drives the traffic.
func (p *PartialColumnBroadcaster) ActionReasonCounts() (rows, cols map[blocks.ActionReason]int) {
	return p.actionReasons.snapshot()
}

// FoldActionReasons sums the counts whose reason set includes every bit of want. Because the keys
// are sets, asking for ReasonAvailabilityAdd counts actions that also carried cells -- which is the
// right question when the interest is "how many messages did availability news cause".
func FoldActionReasons(counts map[blocks.ActionReason]int, want blocks.ActionReason) int {
	total := 0
	for reason, n := range counts {
		if reason.Has(want) {
			total += n
		}
	}

	return total
}
